/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Attack": "攻击",
    "Gyrating Cabins": "旋转小屋",
    "Name": "姓名（仅英文或数字）",
    "Save & load game": "保存 & 加载游戏",
    "Source code": "源码",
    "You need to enable JavaScript to run this app.": "你需要启用JavaScript来运行这个应用程序。",
    "The darkness stirs.": "黑暗涌动。",
    "About": "关于",
    "Reset": "重置",
    "Android of Wrath": "愤怒的机器人",
    "Attributes": "属性",
    "Braindead Alligator": "脑死亡的鳄鱼",
    "Collect loot": "收集战利品",
    "Dying Hooligan": "死掉的流氓",
    "Everything is dead.": "全都死完了。",
    "Go to ???": "前往 ???",
    "health": "生命值",
    "Health": "生命值",
    "in": "在",
    "Nothing is left.": "什么都没有留下。",
    "per": "每",
    "Progress": "进度",
    "Recovery rate": "治愈率",
    "Regenerating": "再生",
    "regeneration": "再生",
    "Remains": "仍然是",
    "Resting": "休息",
    "Retreat": "撤退",
    "Stage": "关卡",
    "Total attack rate": "总攻击速率",
    "Total damage": "总伤害",
    "Attack rate:": "攻击速率：",
    "attack rate.": "攻击速率。",
    "Attribute": "属性",
    "Available attribute points": "可用属性点",
    "Buy": "购买",
    "Caravan": "商队",
    "Current": "当前",
    "Damage:": "伤害:",
    "Endurance": "耐力",
    "essence and required essence for next attribute point.": "精华和下一个属性点所需的精华。",
    "Greetings. I have what you're looking for.": "你好。我有你要找的东西。",
    "health.": "生命值。",
    "Increases": "增加",
    "Increases maximum": "增加最大",
    "Melting Pitchfork": "融化的干草叉",
    "Merchant": "商人",
    "Nothing to sell.": "没什么可卖的。",
    "Power level": "战力等级",
    "Price": "价格",
    "Purchase items": "购买物品",
    "Rank": "等级",
    "Reduces": "减少",
    "Requires a skill.": "需要一个技能。",
    "Return to wilderness": "返回荒野",
    "Sell items": "出售物品",
    "Speed": "速度",
    "stamina.": "耐力。",
    "Strength": "力量",
    "Trade": "交易",
    "Vitality": "活力",
    "Weapon": "武器",
    "weapon damage.": "武器伤害。",
    "Burden:": "负重:",
    "Equipped": "已装备",
    "Equipped weapon": "已装备的武器",
    "Nothing available.": "暂无可用。",
    "Sell": "出售",
    "Bile Mirage": "胆汁幻境",
    "Gruelling Abyss of the Devastated": "残酷的毁灭深渊",
    "Monster": "怪物",
    "Monster attack rate": "怪物攻击速率",
    "Monster damage": "怪物伤害",
    "Monster health": "怪物生命值",
    "Putrid Masochist of Malice": "邪恶的受虐狂",
    "TOTAL": "总计",
    "Armor": "护甲",
    "Effluent Cuisses": "废水腿甲",
    "Go to caravan": "前往商队",
    "Hello again. Some protection, perhaps?": "又见面了。也许你需要一些保护措施？",
    "Insufficient essence.": "精华不足。",
    "Loot": "战利品",
    "Protection:": "防护:",
    "Base:": "基础:",
    "Looted essence": "掠夺的精华",
    "Looting": "掠夺中",
    "Monster regeneration": "怪物回血",
    "Oppressed Cybermage": "被压迫的赛博法师",
    "Scabrous Betrayer": "粗暴的背叛者",
    "stamina": "耐力",
    "Steaming Narwhal": "蒸汽独角鲸",
    "Vitality:": "活力:",
    "Windbag's Road": "风言风语之路",
    "Essence after": "",
    "loot collection and required essence for next attribute point.": "战利品收集后的精华和下一个属性点所需的精华。",
    "Absorbed essence": "吸收的精华",
    "Ah, you're back. Care for something to fend off attacks?": "啊，你回来了。需要一些东西来抵御攻击吗？",
    "Block chance:": "格挡几率:",
    "Equipped armor": "已装备的护甲",
    "Essence": "精华",
    "On attack:": "攻击时:",
    "Ripped Ward": "撕裂病房",
    "Shield": "盾牌",
    "Strength:": "力量:",
    "Total protection": "总计防护",
    "Archaic Boulevard": "古风大道",
    "Demented Blasphemer": "疯狂的亵渎者",
    "Fledgling Eye": "羽翼之眼",
    "gear.": "装备.",
    "Knapsack": "背包",
    "Need a way to manage your possessions?": "需要一种方法来管理你的财产吗?",
    "Provides space for items and the ability to manage": "提供放置物品的空间和管理能力",
    "Recovering ...": "恢复中…",
    "Relic": "遗物",
    "Whistling Gnome": "吹口哨的侏儒",
    "BLOCKED": "格挡",
    "Horrid Brigand": "可怕的强盗",
    "New attribute points": "新属性点",
    "Rusty Depths": "锈色深渊",
    "Speed:": "速度:",
    "Singing Wisp": "歌唱的小精灵",
    "Speedy Observer": "极速观察者",
    "Total block chance": "总计格挡几率",
    "Weapon:": "武器:",
    "Stamina": "耐力",
    "bandages.": "绷带。",
    "Crew for hire": "酒馆",
    "Crew member": "佣兵",
    "Found on": "发现于",
    "Hire": "雇佣",
    "Heard there are other travelers looking to sell their services.": "听说还有其他旅行者想要出售他们的服务。",
    "Hired crew": "雇佣人员",
    "Medic": "医疗兵",
    "mending and sells": "治疗和出售",
    "Offers": "提供",
    "Value": "价值",
    "\"The meaning of life is that it ends.\"": "“生命的意义在于它的终结。”",
    "corpse decorates the battlefield, ripe for scavenging.": "尸体装饰着战场，等待被清理。",
    "Endurance:": "耐力:",
    "essence is lost.": "精华丢失了。",
    "Flatline": "挂了",
    "Low": "低",
    "Memories and": "回忆与",
    "Off-kilter Illusionist": "变态魔术师",
    "Rebirth": "重生",
    "possessions are retained.": "财产被保留。",
    "Tardigrade of Fear": "恐惧的缓步动物",
    "The wilderness is shifting ...": "荒野正在变迁……",
    "Unspent": "没有用完的",
    "Volcano of Blight": "枯萎火山",
    "Flaccid Wight": "柔弱的巫妖",
    "Hoarder of Chaos": "混乱囤积者",
    "Hollow Cesspool": "空心污水池",
    "Insectoid Horror": "虫族恐怖",
    "Joyful Chameleon": "快乐的变色龙",
    "Prince of the Storm": "风暴王子",
    "Scarecrow of Combustion": "燃烧的稻草人",
    "Scavenge corpse": "清理尸体",
    "New gear for sale, if you care to peruse.": "有新装备出售，如果你愿意仔细看看的话。",
    "Mouldering Voulge": "腐朽的峡谷",
    "Wriggly Beast": "扭动的野兽",
    "Plenty of monsters out there.": "外面有很多怪物。",
    "Peninsula": "半岛",
    "Musky Necromancer": "麝香死灵法师",
    "Muddy Chestpiece": "泥泞胸衣",
    "Devastated Chomper": "破坏咀嚼者",
    "\"I'm feeling a bit useless here ...\"": "“我觉得自己在这儿有点没用……”",
    "Alleviates": "缓解",
    "Always leave some extra space for unexpected finds.": "总是为意想不到的发现留一些额外的空间。",
    "Demon's Prison": "恶魔的监狱",
    "encumbrance by expanding the": "通过扩大负重",
    "I've happened upon a relic allowing you to retread old ground.": "我偶然发现了一件遗物，可以让你翻新旧地。",
    "Jester of Lamentation": "恸哭的小丑",
    "knapsack.": "背包。",
    "Scintillating Phoenix": "闪烁的凤凰",
    "Starfish of Oblivion": "湮灭的海星",
    "Stitch": "缝合",
    "Tailor": "裁缝",
    "Allows": "允许",
    "Compass": "指南针",
    "navigation of the": "导航",
    "wilderness to explore previous locations.": "荒野，探索之前的地点",
    "Discard": "丢弃",
    "Encumbrance": "负重",
    "Inventory": "背包",
    "Stored": "已存储",
    "Too heavy.": "太重了。",
    "Unequip": "脱下",
    "Weight:": "重量:",
    "Expand": "扩展",
    "Add pockets": "增加口袋",
    "Charred Palisade": "烧焦的栅栏",
    "Mechanical Succubus": "机械女妖",
    "Mindbreaker": "思维破坏者",
    "Monk's Tomb": "僧人墓",
    "Queen of the Aether": "以太女王",
    "There is something looming on the horizon ...": "地平线上隐约出现了什么东西。",
    "When struck:": "被击中时：",
    "A powerful presence looms.": "一个强大的存在隐约出现。",
    "Adds an elemental": "添加一个元素",
    "effect:": "效果:",
    "fire": "火",
    "bonus to damage, thorns and duration": "伤害加成，荆棘加成，持续时间加成",
    "Freshslither, the Vapor": "新鲜滑溜，蒸汽",
    "gear level": "装备等级",
    "Gem": "宝石",
    "Import & export savegame file": "导入&导出存档文件",
    "Malevolent Cesspit": "恶毒的粪坑",
    "Monster cannot regenerate": "怪物无法回复",
    "Ruby": "红宝石",
    "Sockets into": "镶嵌到",
    "The game is saved in browser memory at all times, persisting through window closure and page reloads.": "游戏一直保存在浏览器内存中，通过窗口关闭和页面重新加载持续存在。",
    "thorns based on": "基于荆棘的",
    "weapon damage": "武器伤害",
    "When blocking:": "格挡时：",
    "Socket": "镶嵌",
    "Allow me to patch you up.": "让我帮你包扎一下。",
    "I can't believe you came out of that in one piece.": "真不敢相信你竟然毫发无损地出来了。",
    "Old Ram": "老羊",
    "Treat": "治疗",
    "Butchering Basilisk of the Moon": "屠戮月亮蛇怪",
    "Cutthroat": "屠戮者",
    "damage per second of all creatures.": "伤害每秒对于所有生物。",
    "Discerns": "辨别",
    "Elite Burrow of the Flensed": "精英剥皮者的洞穴",
    "Equip": "装备",
    "Fine craftsmanship in this little gadget ...": "这个小玩意儿做工精细……",
    "Raucous Dragon of Devastation": "沙哑的毁灭之龙",
    "Thaumaturgic Goggles": "奇迹的护目镜",
    "Attack rate": "攻击速率",
    "Blacksmith": "铁匠",
    "Block chance": "格挡几率",
    "Blunt": "钝器",
    "Class": "类型",
    "Class:": "类型:",
    "Craft": "制作",
    "Craft gear": "制作装备",
    "Crafts and identifies": "制作和标识",
    "Discard item?": "丢弃物品?",
    "Entombed Archmage": "被埋葬的大术士",
    "Forge": "锻造",
    "Gear level:": "装备等级:",
    "Heavy": "重型",
    "Have you appraised all my offerings?": "我所献的一切，你都鉴赏了吗？",
    "In need of better gear?": "需要更好的装备？",
    "Incorporeal Grounds": "无形的理由",
    "King of Fury": "狂暴之王",
    "Light": "轻型",
    "Medium": "中型",
    "Piercing": "穿刺",
    "Reinforced": "强化",
    "Melting Pitchfork will be lost forever.": "融化的干草叉将永远消失。",
    "Sagging Specter": "下垂的幽灵",
    "Slashing": "劈砍",
    "Small": "小型",
    "Tower": "巨型",
    "Burden": "负重",
    "Damage": "伤害",
    "Protection": "防护",
    "Gear level": "装备等级",
    "Weight": "重量",
    "Already at full health.": "已经满血了。",
    "Bandages": "绷带",
    "Buy back items": "回购物品",
    "Bone Insect": "骨虫",
    "Dysfunctional Necromancer": "功能失调的死灵法师",
    "Equipped shield": "已装备的盾牌",
    "Eradicate": "摧毁",
    "Fully restores": "完全恢复",
    "health and": "生命值和",
    "If injured, fully restores": "如果受伤，完全恢复",
    "Mending": "修补",
    "Operate": "操作",
    "Receive mending": "接受修补",
    "Purchase bandages": "购买绷带",
    "Small Moon": "小月亮",
    "Surgery": "外科手术",
    "Wasted Outlaw": "废柴流亡者",
    "Armor:": "护甲:",
    "Navigate": "导航",
    "The needle is spinning.": "针正在旋转。",
    "EXHAUSTED": "筋疲力尽",
    "Requires a screen width of minimum 1,200 pixels.": "要求屏幕宽度至少为1200像素。",
    "Grove of the Desperate": "绝望的丛林",
    "Livid Stingray": "青黄貂鱼",
    "Mercenary of Doom": "末日雇佣兵",
    "Awful Renegade of Torture": "可怕的酷刑叛徒",
    "Ripping Rogue of Extermination": "Ripping Rogue of Extermination",
    "Defiant Mage": "挑衅的法师",
    "Interceptor of the Cinders": "灰烬拦截者",
    "Antagonist of Cruelty": "残忍的反对者",
    "Strong Centipede": "强大的蜈蚣",
    "Wispish Cacodemon": "飘渺的恶魔",
    "Lost memories held close unlock pathways to remarkable discoveries ...": "失去的记忆紧紧地锁住了通往非凡发现的道路……",
    "Sad Juggler": "可悲的骗子",
    "Triumphant Dryad": "胜利的森林女神",
    "Memento": "纪念品",
    "Hothead of Mischief": "鲁莽的恶作剧者",
    "Eradicate item?": "摧毁物品？",
    "Abandoned Midget of Bane": "被遗弃的贝恩侏儒",
    "Martyr of Fear": "恐惧殉道者",
    "Perilous Castle": "危险的城堡",
    "Wanderer of Sacrilege": "亵渎神灵的流浪者",
    "Apoplectic Convict": "中风的罪犯",
    "Microscopic Cockroach": "微型蟑螂",
    "Navigate the wilderness": "穿越荒野",
    "Robot of Avulsion": "崩裂机器人",
    "Sorrowful Ziggurat": "悲伤的金字神像",
    "Bay": "海湾",
    "Fiend of the Dark": "黑暗恶魔",
    "CANNOT BLOCK": "无法阻挡",
    "Dinosaur of Terror": "恐怖恐龙",
    "Illustrious Potato": "杰出的土豆",
    "Oppressive Vixen": "压迫的泼妇",
    "Pulsating Cultist": "脉动崇拜者",
    "Wiggly Terminator": "扭动终结者",
    "A relic that grants safe passage. Would that be of interest?": "一个能让你安全通行的圣物。你会感兴趣吗？",
    "Hearthstone": "炉石传说",
    "Instantly travel back to the": "瞬间旅行回到",
    "caravan regardless of any": "商队不管任何",
    "lurking monsters.": "潜伏的怪物。",
    "Beguiling Themepark of Death": "死亡主题公园",
    "Buff Cabalist": "浅黄色秘术家",
    "Bulbous Bishop": "球根状的主教",
    "Calm Windbag": "平静的饶舌之人",
    "Corpse location": "尸体的位置",
    "Corrupt Nephalim": "堕落的奈法利姆",
    "Dead monster": "死去的怪物",
    "Effigy of the Night": "夜的雕像",
    "Enlightened Muffin": "开明的松饼",
    "Enraged Raver": "愤怒的说胡话的人",
    "Explosive Roughneck": "爆炸性的粗鲁的人",
    "Frantic Watcher": "疯狂的观察者",
    "Gangster of the Brine": "盐水强盗",
    "Hedonist Meteor": "享乐主义者的流星",
    "Hopeful Monster": "充满希望的怪物",
    "Horrid Automaton": "可怕的自动机",
    "Lurking monster": "潜伏的怪物",
    "Monstrous Alligator": "巨大的鳄鱼",
    "Noisome Gargantuan of Annihilation": "可怕的巨兽湮灭",
    "Obstinate Horror": "顽固的恐怖",
    "Pest of Darkness": "黑暗害虫",
    "Purulent Terminator": "化脓性终结者",
    "Sea Stalker of Fury": "狂暴的海上潜行者",
    "Semi Artificer": "半技工",
    "Squelching Black Hole": "无声的黑洞",
    "Stone Worlds": "石头的世界",
    "Swollen Neophyte": "肿胀的新手",
    "Writhing Guardian": "扭动监护人",
    "Attic of the Empty": "空阁楼",
    "Excited Martyr": "兴奋的烈士",
    "Flower of Sin": "罪恶之花",
    "Pulsating Stranger": "脉动的陌生人",
    "Reptoid of Lamentation": "哀叹的副本",
    "Wrinklewiggle, the Treant": "皱纹怪，树怪",
    "Abyssal Phantom of Annihilation": "深渊幻影湮灭",
    "Annihilating Butcher": "湮灭屠夫",
    "Artificer": "人工操作者",
    "Barbed Bureaucrat": "带刺的官僚",
    "Boss": "Boss",
    "Chaotic Knight": "混沌骑士",
    "Chittering Sell-sword": "喋喋不休的买卖剑",
    "Colossal Neophyte of Purulence": "巨大的脓性新生生物",
    "Dead boss": "死的老板",
    "Deaf Nephalim": "聋人奈法利姆",
    "Decaying Apprentice of Sickening": "腐烂的学徒，令人作呕",
    "Diuretic Mannequin": "利尿剂人体模型",
    "Gorgon of Fright": "惊恐的蛇发女妖",
    "Griffin of Killing": "杀戮狮鹫",
    "Gurgling Archpriest": "潺潺犯事",
    "Honorable Bureaucrat": "尊敬的官员",
    "Hulk of Combustion": "燃烧的残骸",
    "Hunted Dinosaur": "猎杀恐龙",
    "Hunting Demon of Ice": "冰之猎魔",
    "Icy Throat-wolf": "冰喉狼",
    "Insipid Stabber": "平淡的刺客",
    "Jigglemaster, the Bastard": "小霸王，混蛋",
    "Kobold of Spawning": "狗头人的产卵",
    "Lanky Bully": "瘦长的欺负",
    "Leper of Flatulence": "肠胃胀气的麻风病人",
    "Lurking Fish": "潜伏的鱼",
    "Miserable Vanguard": "悲惨的先锋",
    "Moth of Justice": "正义之蛾",
    "Mummified Magician": "木乃伊化的魔术师",
    "Munchmeat, the Reptoid": "咀嚼肉，爬虫类动物",
    "Obliging Leper of Dreariness": "沉闷的顺从麻风病人",
    "Paradise Brigand": "天堂强盗",
    "Puzzled Cutthroat": "困惑的杀手",
    "Scornful Potato": "轻蔑的土豆",
    "Servitor of Anguish": "痛苦的仆人",
    "Squelchstab, the Juggernaut": "寂刺，神之神",
    "Toddlejuice, the Scoundrel": "蹒跚学步，恶棍",
    "Voluptuous Oddity": "性感的古怪",
    "Wailskull, the Crone": "壁头骷髅，老妪",
    "Warp": "扭曲",
    "Whimpering Sell-sword": "呜咽的出卖之剑",
    "Windbag of the Night": "夜话唠",
    "Wise Autophage": "明智的自噬体",
    "Xenomorph of Twilight": "暮光之异体",
    "Battering Humanoid": "打击人形",
    "Belchmuffle, the Condemned": "贝尔奇马弗，死刑犯",
    "Bilgetooth, the Mime": "毕吉牙，哑剧演员",
    "Blightfart, the Doorknob": "鬼屁，门把手",
    "Bungledread, the Ninja": "笨拙恐惧，忍者",
    "Calamitous Goon": "灾难性的呆子",
    "Campsite of the Werebears": "熊人的营地",
    "Charlatan of Fear": "恐惧的江湖骗子",
    "Coward": "懦夫",
    "Damage per second:": "每秒伤害：",
    "Dinosaur of Sickening": "令人作呕的恐龙",
    "Dusty Shadow of the Hopeless": "无望的尘埃阴影",
    "Flailing Demigod": "摇摇欲坠的半神半人",
    "Grimy Reliquary": "肮脏的圣髑盒",
    "Hatesquelch, the Carnivore": "仇恨鬼，食肉动物",
    "Hedonistic Mirage": "享乐主义的海市蜃楼",
    "Hell Scoundrel": "地狱的恶棍",
    "Hexing Betrayer": "禾欣叛徒",
    "Manglehack, the Brawler": "莽客，斗殴者",
    "Mindbreaker's Cul-de-sac": "破坏者的死胡同",
    "Old Mage": "老法师",
    "Pestsack, the Maiden": "佩萨克，少女",
    "Purple Warlord": "紫色的军阀",
    "Ragged Hell": "衣衫褴褛的地狱",
    "Ratcrazy, the Machine": "疯狂的老鼠，机器",
    "Rathead, the Autophage": "更确切地说，是自噬",
    "Reptoid of the Nether": "地狱的爬虫",
    "Repulsive Scribe": "令人厌恶的抄写员",
    "Sackstink, the Cyclops": "萨克臭味，独眼巨人",
    "Shinglesmear, the Wanderer": "流浪者，希勒斯米尔",
    "Shinglesqueak, the Scion": "shinglesquak，司祭盎",
    "Sneezemaul, the Outlaw": "鼻涕虫，亡命徒",
    "Sphinx of Torment": "折磨的斯芬克斯",
    "Stompreave, the Satyr": "森林之神",
    "Wizzbungle, the Siren": "巫师班格，海妖",
    "Yeetcraze, the Cockroach": "耶奇，蟑螂",
    "Anatomy": "解剖学",
    "Armorcraft": "盔甲制作",
    "Assassination": "暗杀",
    "attributes.": "属性。",
    "Avian of Fortune": "幸运之鸟",
    "Bear of Deceit": "欺骗之熊",
    "bleeding with": "流血",
    "Blood-soaked Conqueror": "血腥征服者",
    "Blue Guard": "蓝色的警卫",
    "blunt weapons, reducing their chance to hit.": "钝化武器，降低其命中几率。",
    "Brigand of Lamentation": "恸哭的强盗",
    "Calisthenics": "健身操",
    "Carcass of Loathing": "厌恶的尸体",
    "chance and": "机会,",
    "Cowardly Pirate": "懦弱的海盗",
    "critical strikes with two new attributes:": "暴击有两个新属性：",
    "Crystal Sponge": "水晶海绵",
    "damage.": "伤害。",
    "dexterity for": "灵巧",
    "Diabolical Eye": "恶魔的眼睛",
    "dodge attacks, avoiding all damage.": "躲避攻击，避免所有伤害。",
    "Drunk Werebear": "喝醉的熊人",
    "Escrime": "击剑",
    "Evasion": "规避",
    "execute monsters when they reach low": "当怪物到达低位时执行",
    "Figment of Regurgitation": "虚构的反流",
    "Flailing Cadaver of Frost": "霜冻的尸体",
    "Frog of Sin": "罪恶之蛙",
    "Gory Vixen": "血淋淋的泼妇",
    "Grants the": "资助的",
    "Grants the ability to": "授予能力去",
    "Grants the ability to deal": "授予能力造成",
    "Grants the ability to inflict": "授予能力施加",
    "Grants the use of": "授予使用",
    "Grotesque Battlemage of Desolation": "荒凉的怪诞战斗法师",
    "heavy armor and the ability to improve": "重甲和提升能力",
    "Humanoid Scarecrow": "人形稻草人",
    "I can teach, if you can learn.": "如果你能学，我也能教。",
    "Inescapable Executioner": "不可避免的刽子手",
    "Lurking boss": "潜伏的老板",
    "Marauder of Fortune": "劫掠者",
    "Marinated Xenophobe": "腌制仇外",
    "Mercenary": "雇佣兵",
    "Minion of the Storm": "风暴仆从",
    "Moaning Lord": "呻吟的主",
    "Monster damage per second": "怪物每秒伤害",
    "Necrophage of Restraint": "抑制性Necrophage",
    "Nightmare of Loneliness": "孤独的噩梦",
    "Orcish Bear": "兽人熊",
    "parry attacks with": "用",
    "perception for": "知觉的",
    "piercing weapons, dealing periodic damage.": "穿刺武器，造成周期性伤害。",
    "Pleasure Unicorn": "快乐的独角兽",
    "Pundit of the Expanse": "广袤无垠的权威",
    "recovery.": "复苏。",
    "regeneration rate of": "再生速率",
    "Requires a crew member.": "需要一名船员。",
    "Screeching Plant": "刺耳的植物",
    "Shieldcraft": "护盾制作",
    "Siegecraft": "护盾制作",
    "skills and unlocks": "技能和解锁",
    "slashing weapons, partially avoiding and reflecting damage.": "砍砍武器，部分避免和反射伤害。",
    "Spirit of the Abyss": "深渊之灵",
    "stagger monsters, reducing their damage dealt.": "错开怪物，减少他们的伤害。",
    "stun monsters with": "用击晕怪物",
    "Three-legged Coward": "三条腿的懦夫",
    "tower shields with the ability to": "塔盾有能力",
    "Train": "训练",
    "Train skills": "训练技能",
    "Trains": "训练",
    "Traumatology": "创伤学",
    "Triumphant Pariah of Screams": "胜利的尖叫贱民",
    "two-handed melee weapons that": "双手近战武器",
    "vigor attribute that increases the": "活力属性，提升",
    "Affects": "影响",
    "Bile Shaman": "胆汁萨满",
    "bleed damage.": "流血伤害。",
    "Cruelty": "残酷",
    "Desolate Maiden": "荒凉的少女",
    "Elemental of Hedonism": "享乐主义的元素",
    "Ingenious Shambler": "巧妙的蔓生怪",
    "Janitor of Misfortune": "不幸的看门人",
    "Masteries": "精通",
    "Mechanical Carnivore": "机械食肉动物",
    "Pain Warmonger": "痛苦的战争贩子",
    "piercing weapon.": "锐利的武器。",
    "Punished Monk": "惩罚和尚",
    "Septic Antagonist": "脓毒性拮抗物",
    "Serpentine Barbarian": "蜿蜒的野蛮人",
    "Skill": "技能",
    "Skills": "技能",
    "Trained skills": "培训技能",
    "Trains when dealing damage with a": "训练如何使用",
    "Twisted Juggernaut": "扭曲的力量",
    "Wandering Herald": "流浪的先驱",
    "Attributes & skills": "属性&技能",
    "Mastery": "精通",
    "Armorer of the Blighted": "枯萎的军械师",
    "Bastard of the Culling": "被淘汰的混蛋",
    "Capabilities": "能力",
    "Pestilent Cadaver": "瘟疫尸体",
    "Radiant Puppet": "闪耀人偶",
    "Saggy Pariah": "松垮的贱民",
    "Siren of Ice": "冰妖",
    "Snotty Hexmage": "鼻涕法师",
    "Speedy Metamorph": "快速变形",
    "Xenomorph of Rot": "腐病的异型",
    "Determines your basic status.": "决定你的基本状态。",
    "Determined primarily through": "决定方式主要通过",
    "Determined by the equipped ranged weapon and can be increased by mastering": "由所装备的远程武器决定，可通过精通提升",
    "determining the pace of combat. \"2 slots\" means the weapon cannot normally be wielded alongside a": "决定战斗的节奏。“2个插槽”意味着该武器通常不能一起使用与",
    "Dexterity": "灵巧",
    "dexterity": "灵巧",
    "Displays the expected damage per second you (and the monster) can deal, taking into account": "显示你（和怪物）每秒能造成的预期伤害",
    "progress": "进度",
    "Primarily spent on acquiring attribute ranks. Essence cost increases for every allocation of an attribute rank. Also used to trade at the": "主要用于获取属性等级。每分配一个属性等级，精华成本就会增加。也用于交易",
    "progress. Its duration is determined by the": "的进度。它的持续时间由",
    "Quests": "任务",
    "Quests are categorized into the following:": "任务分为以下几类：",
    "Provide a permanent effect of some sort while they are carried in the inventory. If such a relic is sold or discarded, the effect disappears with it.": "在背包中携带时，提供某种永久效果。如果这样的遗物被出售或丢弃，该效果也随之消失。",
    "Quests are similar to achievements in that they have a set of requirements and track progress based on your progress and circumstances. They are unlocked once the journal": "任务类似于成就，因为它们有一系列要求，并根据你的进度和环境来跟踪进度。一旦日志被解锁",
    "range": "范围",
    "ranged": "远程",
    "Range": "范围",
    "ranged weapon": "远程武器",
    "ranged weapons": "远程武器",
    "Ranged weapons": "远程武器",
    "rate is increased when not wearing any armor, effectively reducing the amount of attribute points required in": "率增加当不穿任何护甲，有效地减少了所需的属性点数",
    "Recovery": "恢复",
    "recovery": "恢复",
    "Recovery occurs when damage is dealt, halting regeneration of": "当受到伤害时恢复，停止回复当",
    "Agility:": "敏捷：",
    "Angelic Fjord of Fortune": "天使的幸运峡湾",
    "Atrocious Boot": "残暴的靴子",
    "Crusty Palisade": "硬皮栅栏",
    "Dodge chance": "闪避几率",
    "Elemental:": "元素:",
    "Illustrious Drill": "杰出的钻",
    "On dodge:": "闪避:",
    "Agility": "敏捷",
    "dodge an attack.": "闪避一次攻击。",
    "Increases chance to": "提高几率去",
    "regeneration rates of": "回复速率",
    "Vigor": "活力",
    "Vigor:": "活力:",
    "Reset quest?": "重置冒险？",
    "Stores": "商店",
    "Advisor": "顾问",
    "Anguished Bloodsucker": "痛苦的吸血鬼",
    "Armored Fungus": "装甲真菌",
    "Atrocity Starfish": "暴行海星",
    "Autophagic King": "自噬的国王",
    "Bad Cenobite": "坏的修道士",
    "Balrog of Liberation": "解放魔魔",
    "Base rate:": "基础速率:",
    "Bear of the Culling": "挑选的熊",
    "Beastly Rook": "可恶的骗子",
    "Bedazzled Corvid": "眼花缭乱的种",
    "Bellowing Bloodseeker": "咆哮的寻血者",
    "Bilious Crab": "胆汁的螃蟹",
    "Blistered Rook": "起泡的车",
    "Bold Impaler": "大胆的插入物",
    "Busty Crocodile": "胸部丰满的鳄鱼",
    "Buzzing Marionette": "嗡嗡的木偶",
    "Calm Kraken": "平静的海妖",
    "Chained Reaper": "链接收割者",
    "Chattering Hierophant": "喋喋不休圣职者",
    "Chomping Odor": "迫不及待的气味",
    "Clandestine Zombie": "秘密的僵尸",
    "Clockwork Weirdo": "发条怪人",
    "Clumsy Potato": "笨拙的土豆",
    "Combusting Cyclops": "燃烧独眼巨人",
    "Crab of Butchery": "屠宰蟹",
    "Cranky Cultist of Mischief": "古怪的恶作剧崇拜者",
    "Creep of the Cold": "寒冷的蔓延",
    "Creep of the Nether": "地狱的怪物",
    "Cripple of Lamentation": "悲叹残废",
    "Cubic Reaver": "立方掠夺者",
    "Cyan Jailer of Lightning": "青色的闪电狱卒",
    "Decadent Bishop": "颓废的主教",
    "Decapitated Serpent": "斩首蛇",
    "Decayed Doorknob": "腐烂的门把手",
    "Delightful Cadaver": "令人愉快的尸体",
    "Demon of Darkness": "黑暗恶魔",
    "Detestable Balrog": "可憎的炎",
    "Detonating Beholder": "引爆旁观者",
    "Disastrous Fork": "灾难性的叉",
    "Dishevelled Arsonist": "蓬乱的纵火犯",
    "Doll of Devastation": "毁灭娃娃",
    "Drake of Chaos": "混乱之龙",
    "Drowned Golem": "淹死的傀儡",
    "Dwarven Watcher": "矮人观察家",
    "Dysfunctional Scion": "功能失调的后裔",
    "Eldritch Knight": "可畏的骑士",
    "Emaciated Gobbler": "瘦弱的雄火鸡",
    "Exterminator of Scorn": "消灭轻蔑者",
    "Fairy of the Labyrinth": "迷宫仙女",
    "Farting Apparition": "放屁的幻影",
    "Farting Monk": "放屁和尚",
    "Fastidious Roughneck": "挑剔的粗鲁的人",
    "Festering Corvid": "不断恶化的种",
    "Flaccid Skullshield": "松弛的骷髅",
    "Flatulent Bloodletter": "肠胃气胀的血书",
    "Flayed Serpent": "剥皮的蛇",
    "Flensed Amoeba": "剥皮变形虫",
    "Fletcher": "造箭者",
    "Flowery Avatar": "绚丽的化身",
    "Flummoxed Sadist": "困惑的施虐狂",
    "Frantic Metamorph": "疯狂变身",
    "Frenzied Vapor of Corruption": "疯狂的腐败蒸汽",
    "Furry Seraph": "毛茸茸的六翼天使",
    "Gelatinous Mage": "凝胶状的法师",
    "Glamorous Jailer of Insolence": "迷人的傲慢狱卒",
    "Glimmering Dragon": "闪烁的龙",
    "Gobbler of Surprises": "惊喜饕餮",
    "God of Ice": "冰之神",
    "Great Sell-sword": "伟大的出卖之剑",
    "Grotesque Dwarf": "奇形怪状的矮",
    "Harpy of Cruelty": "残忍女妖",
    "Harpy of Disease": "疾病之女妖",
    "Harvesting Carcass": "收获的尸体",
    "Hedonist of the Void": "虚空的享乐主义者",
    "Hedonistic Monster": "享乐主义的怪物",
    "Herald of the Abyss": "深渊使者",
    "Here is something suitable for marksmen.": "这是适合射手的东西。",
    "Hexmage of Sacrilege": "亵渎法师",
    "Hexproof Soldier": "六角兵",
    "Horrifying Alien": "恐怖的外星人",
    "Humongous Mutineer": "巨大无比的反抗者",
    "Hunted Effigy": "猎杀雕像",
    "Hysterical Simulacrum": "歇斯底里的影",
    "Illustrious Charlatan": "杰出的骗子",
    "Impaled Sell-sword": "出卖之剑",
    "Impoverished Robot": "贫困的机器人",
    "Inescapable Leviathan": "不可避免的利维坦",
    "Infected Hydra": "受感染的九头蛇",
    "Interstellar Ogre": "星际食人魔",
    "Jade Smoker": "玉吸烟者",
    "Jagged Flower": "锯齿状的花",
    "Jelly Prince of Discombobulation": "混乱的果冻王子",
    "Jester of the Culling": "剔除的小丑",
    "Lanky Squid": "瘦长的鱿鱼",
    "Liberator of Fear": "恐惧的解放者",
    "Licentious Fanatic": "放肆的狂热分子",
    "Lich of Restraint": "克制巫妖",
    "Licking Siren": "舔海妖",
    "Liquid Plant": "液体植物",
    "Lonely Wizard": "孤独的向导",
    "Lousy Waistwrap": "糟糕的马甲",
    "Ludicrous Tumor": "可笑的肿瘤",
    "Lurid Spawn": "耸人听闻的产卵",
    "Maddened Terror": "这激怒了恐怖",
    "Mangy Xenophobe": "污秽的仇外",
    "Massacre Halfling": "大屠杀半身人",
    "Mist Skin-thief": "薄雾窃贼",
    "Mistreated Coward": "虐待懦夫",
    "Mistreated Rake": "虐待耙",
    "Moaning Horror": "呻吟恐怖",
    "Mongrel of Disease": "疾病的杂种",
    "Monster of Annihilation": "毁灭怪物",
    "Monstrosity of Extirpation": "灭绝怪物",
    "Morose Exterminator": "郁闷的灭鼠药",
    "Morose Lunatic": "忧郁的疯子",
    "Mummy of Combustion": "燃烧木乃伊",
    "Munitions Satchel": "弹药书包",
    "munitions to fire": "发射弹药",
    "Mushroom of Calamity": "灾难蘑菇",
    "Mushroom of Danger": "危险蘑菇",
    "Mutant Odor": "突变体的气味",
    "Mutineer of Dysfunction": "机能失调的叛变者",
    "Necrotic Wizard": "坏死的向导",
    "Nocturnal Cenobite": "夜间修道士",
    "Obscure Pyromaniac": "模糊放火狂",
    "Obstinate Gobbler": "固执狼吞虎咽的",
    "Occultist of Entropy": "熵的神秘主义者",
    "Odd Doorknob": "奇怪的门把手",
    "Outlandish Torturer": "古怪的虐待者",
    "Outsider of Sorrow": "悲伤的局外人",
    "Plagued Pawn": "困扰典当",
    "Psychotic Dreadnought": "精神病无畏",
    "Psychotic Vigilante": "精神病治安",
    "Pugnacious Nomad": "好斗的游牧",
    "Raging Lunatic": "狂暴的疯子",
    "Rambunctious Seraph of Flatulence": "狂暴的胀气六翼",
    "ranged weapons.": "远程武器。",
    "Raver of the Aether": "以太的掠夺者",
    "Redeemed Fighter": "救赎战斗机",
    "Regeneration:": "回复：",
    "Regurgitating Beast": "反刍兽",
    "Renegade of Extermination": "灭绝的叛徒",
    "Repulsive Dreadknight": "可恶的恐怖骑士",
    "Rogue Tyrannosaurus": "流氓暴龙",
    "Ruby Spider": "红宝石蜘蛛",
    "Saintly Slaver": "圣洁的口水",
    "Scampering Wyrm": "扫地的妖蛆",
    "Scarlet Ninja": "鲜红的忍者",
    "Screaming Dwarf": "尖叫的矮",
    "Seeping Wretch": "渗透的家伙",
    "Sewer Archon": "下水道执政官",
    "Sewer Conjurer of the Dark": "黑暗的下水道魔术师",
    "Shambler of Fire": "火之漫步者",
    "Shattered Heathen": "破碎的异教徒",
    "Shiny Dreamer of Torture": "折磨的闪亮梦想家",
    "Shrouded Poltergeist": "笼罩吵闹鬼",
    "Sick Cabalist": "生病的法师",
    "Skinning Drone": "剥皮无人机",
    "Smart Shadow": "聪明的影子",
    "Sneezing Conjurer": "打喷嚏的魔术师",
    "Sorceress of Destruction": "毁灭女巫",
    "Sorceress of the Storm": "风暴女巫",
    "Sphinx of the Brine": "盐水的斯芬克斯",
    "Squirming Nightmare": "蠕动的噩梦",
    "Stressed Remnant of Pandemonium": "大混乱的残余",
    "Strong Monstrosity": "强大的怪物",
    "Submissive Armorer": "顺从的军械士",
    "Surgeon of Pain": "疼痛外科医生",
    "Swampy Scepter": "沼泽的权杖",
    "Tall Servitor of Dysfunction": "高大的机能失调者",
    "Tardigrade of the Roil": "水熊虫",
    "Thing of Surprises": "惊喜之事",
    "Tired of monster breath? Don't forget to rearm.": "厌倦了怪物的呼吸？别忘了重新武装。",
    "Toadstool of Hope": "希望毒菌",
    "Tortured Outsider": "折磨的局外人",
    "Trilobite of Pandemonium": "大混乱的三叶虫",
    "Turbulent Pest": "动荡的害虫",
    "Unclean Vanguard of Flatulence": "肠胃胀气的不洁先锋",
    "Unknown Beast": "不知名的野兽",
    "Vapor of the Night": "夜雾",
    "Ventriloquist of Regurgitation": "反流口技者",
    "Warlock of Insolence": "傲慢术士",
    "Warmonger of the Dark": "黑暗战争贩子",
    "Werebear of Extirpation": "灭绝之熊",
    "Whimpering Parasite of Insolence": "傲慢的呜咽寄生虫",
    "Wispish Executioner": "纤弱的刽子手",
    "Wrathful Vigilante": "愤怒的义务警员",
    "Xenophobe": "仇外者",
    "This will reset everything and restart from scratch.": "这将重置所有内容并从头开始。",
    "Affects the": "影响",
    "Burrowing Titan": "穴居泰坦",
    "Disintegrated Amice": "解体披肩",
    "distance a monster must close before it can attack.": "怪物攻击前必须接近距离。",
    "Dried Android": "干燥的安卓",
    "Endless Iceberg": "无尽的冰山",
    "Insectile Dreadnought": "昆虫的无畏",
    "Marksmanship": "枪法",
    "Platinum Skewer": "铂针",
    "ranged weapon.": "远程武器。",
    "Shocked": "震惊了",
    "Smelly Robot": "臭机器人",
    "Wilted Buckler": "枯萎的盾牌",
    "Annihilating Mindbreaker": "毁灭心灵破坏者",
    "Archery": "射箭",
    "Bear of Ceremony": "仪式之熊",
    "Cannot regenerate": "不能再生",
    "critical strike chance.": "暴击几率。",
    "critical strike damage.": "暴击伤害。",
    "Festering Imp": "不断恶化的小鬼",
    "Harlequin of Secrets": "秘密的丑角",
    "Killer of Ceremony": "仪式杀手",
    "Perception": "感知",
    "Restless Wendigo": "不安分的期限",
    "Spoiled Balrog": "被宠坏的炎",
    "Sponge of Dreariness": "沉闷的海绵",
    "Taking 10% increased": "拾取增加10%",
    "Terror of Doom": "末日恐怖",
    "Amethyst": "紫水晶",
    "Dysfunctional Crucifix": "功能失调的十字架",
    "ice": "冰",
    "lightning": "闪电",
    "Monster attack": "怪物攻击",
    "Monster taking 10% increased": "怪物承受增加10%",
    "Munitions cost:": "弹药成本:",
    "Range:": "范围:",
    "rate slowed by 40%.": "速率下降了40%。",
    "Rattling Legplates": "嘎嘎作响的腿板",
    "Sapphire": "蓝宝石",
    "Trebuchet of Devastation": "毁灭投石机",
    "Alchemist": "炼金术士",
    "Brew": "酿造",
    "Converts": "转换",
    "gems between one another. May impart a venerable": "宝石之间。可能会给一个可敬的",
    "I recently came into possession of a fine curiosity.": "我最近得到了一件精美的珍品。",
    "skill.": "技能.",
    "Witch": "女巫",
    "Ender Hook": "末影钩",
    "Infested Saw": "受污染的锯子",
    "looted immediately.": "立即被掠夺。",
    "Monsters are": "怪物",
    "Slimy Targe": "虚伪的圆盾",
    "\"How will you carry around ammo?\"": "“你将如何携带弹药？”",
    "Munitions": "弹药",
    "Ranged": "远程",
    "Acquire": "获得",
    "Experimental Culverin": "实验火枪",
    "MAX": "最大",
    "While": "当",
    "Journal": "日记",
    "quests.": "任务.",
    "Stun": "眩晕",
    "death.": "死亡.",
    "chance:": "几率:",
    "Automincer": "自动机",
    "A compendium of": "的概要",
    "A perplexing ovum emanating otherworldly energy.": "一种散发超凡能量的令人困惑的卵子。",
    "Affects damage": "影响伤害",
    "All enemies that glimpse it become": "所有瞥见它的敌人都会变成",
    "Appraise": "评价",
    "attacking, consumes": "攻击,消耗",
    "Attacks return a fraction of": "攻击返回",
    "avoided and": "避免和",
    "bandages if at low": "绷带很低",
    "blunt weapon.": "钝器。",
    "Collects": "收集",
    "Describes": "描述",
    "Dream Catcher": "追梦人",
    "Eldritch Codex": "可畏的法典",
    "elixir if": "灵丹妙药,如果",
    "enraged.": "激怒了。",
    "equipped and": "装备和",
    "equipped, collects": "装备,收集",
    "exhausted, otherwise": "精疲力尽，否则",
    "Finesse": "技巧",
    "health on being": "关于健康",
    "health or an": "生命值或",
    "Lacrimatory": "催泪",
    "loot and passes to the next": "掠夺并传递给下一个",
    "Might": "可能",
    "Mysterious Egg": "神秘的蛋",
    "noxious foes.": "有毒的敌人。",
    "Outlook of the Flayed": "剥皮者的前景",
    "parrying.": "格挡。",
    "Phylactery": "护符",
    "Puzzling Mortar": "令人费解的砂浆",
    "recovery rate.": "治愈率。",
    "reflected when": "反射时",
    "Resilience": "弹性",
    "Resurrects the bearer upon": "复活携带者",
    "retreats.": "撤退。",
    "Ribbon of Calm": "平静丝带",
    "stage once clear of monsters.": "阶段一次清除怪物。",
    "struck.": "罢工。",
    "stun duration.": "眩晕持续时间。",
    "tears from": "眼泪从",
    "theurgical methodologies beyond comprehension.": "难以理解的神学方法。",
    "Time for contemplation must be made in retirement.": "退休后必须留出沉思的时间。",
    "Torn Manuscript": "撕裂的手稿",
    "total damage as": "总伤害为",
    "Trains when losing": "训练当输了",
    "War Mask": "战争面具",
    "Resilience:": "韧性:",
    "Amoeba of the Void": "虚空的变形虫",
    "attack rate is hastened by 50%.": "攻击速度加快50%。",
    "attack reduced to 50%.": "攻击降低到50%。",
    "Bandit of Screams": "尖叫的强盗",
    "Blessed Caterpillar": "天佑毛虫",
    "Chance to hit on": "几率命中",
    "Chance:": "概率：",
    "Distance": "距离",
    "Duration:": "持续时间:",
    "Effect:": "效果:",
    "Enlightened Cyborg": "开明的改造人",
    "Frailty": "脆弱",
    "Frozen": "冰冻",
    "Grants the ability to decipher and inscribe the": "授予破译和铭文的能力",
    "Grants the ability to perform relic": "授予使用圣物的能力",
    "Graveyard Chupacabra": "墓地“卓帕卡布拉”",
    "Impish Brawler": "顽皮的争吵者",
    "infusion.": "灌注。",
    "journal.": "日记。",
    "Mangler of Jade": "玉石吞噬者",
    "Meditation": "冥想",
    "Memetics": "模因论",
    "Messy Queen of the Aether": "凌乱的以太女王",
    "Obliging Embryo": "乐于助人的胚胎",
    "on": "当",
    "Once enraged,": "一旦被激怒,",
    "Paradoxical Specter": "矛盾的幽灵",
    "Pilgrim of Filth": "污秽的朝圣者",
    "Poison rating": "毒药评级",
    "Rage": "愤怒",
    "Reaper of Cruelty": "残忍的收割者",
    "Retire": "退休",
    "Revolting Scribe": "令人作呕的抄写员",
    "Scruffy Killer": "邋遢的杀手",
    "STUN": "眩晕",
    "Stunned": "眩晕了",
    "Tears": "眼泪",
    "total": "总计",
    "Vigilante of the Brine": "盐水守护者",
    "Yawning Convict": "打呵欠的罪犯",
    "\"Before I can impart protective hexes, you must first taste the bitter tears of experience.\"": "“在我传授保护魔法之前，你必须先尝尝经验的痛苦之泪。”",
    "Antidote": "解药",
    "Consumable": "消耗品",
    "Cryptic relics reveal their true purpose once suffused with essence.": "神秘的遗迹揭示了它们曾经充满精华的真正目的。",
    "Delving further must be our salvation.": "继续钻研一定是我们的救赎。",
    "Elixir": "长生不老药",
    "essence.": "精华。",
    "Flying Marauder of the Expanse": "飞天掠夺者",
    "Godlike Entity": "庄严的实体",
    "Increases munitions by 1.": "增加1点弹药。",
    "Infusion level": "灌注等级",
    "Make": "使",
    "Munitions cost": "弹药成本",
    "Naughty Elemental": "顽皮的元素",
    "New armaments": "新武器",
    "None available.": "没有可用的。",
    "Occultist": "术士",
    "power level to 0, refunding all absorbed": "能量等级为0，全部回收",
    "Purchase phylacteries": "购买护符",
    "Purchase potions": "购买药水",
    "Purge": "清洗",
    "Purge essence": "净化精华",
    "Requires a relic and a skill.": "需要一个圣物和一个技能。",
    "Resets": "重置",
    "Rituals": "仪式",
    "Salacious Goblin": "淫荡的地精",
    "Salve": "药膏",
    "See": "参见",
    "Stored gems": "存储的宝石",
    "Stun chance": "眩晕几率",
    "Tailoring": "裁剪",
    "The oval spawn has the answers you seek.": "椭圆形卵怪有你想要的答案。",
    "The world ends at 75.": "世界末日在75岁。",
    "Train skill": "训练技能",
    "Transmute": "转化",
    "Transmute gems": "转化宝石",
    "Visit": "访问",
    "Worm of Oppression": "压迫虫",
    "1st": "第一",
    "2nd": "第二",
    "Acanthaceous": "棘状",
    "armor is reduced by 50%.": "护甲减少50%。",
    "Base": "基础",
    "Based on current": "基于电流",
    "Bleeding damage is inflicted all at once.": "流血伤害是一次性造成的。",
    "Brawler": "争吵者",
    "Bruiser": "压碎机",
    "Burden from": "负担",
    "Colossus": "巨人",
    "Critical strikes with a": "致命一击",
    "critical strikes.": "关键的罢工。",
    "distance, all attacks with a": "距离，所有的攻击都带着一个",
    "dodge chance is increased by 75%. When dodging, 10% of maximum": "闪避的几率增加75%。闪避时，为最大值的10%",
    "execution threshold.": "执行阈值。",
    "Executioner": "刽子手",
    "Gear": "装备",
    "gems is increased by 65%.": "宝石增加65%。",
    "generation and": "生成和",
    "health is restored.": "健康恢复了。",
    "heavy armor classes.": "重甲职业。",
    "Inherited relics": "继承了遗产",
    "light, 10% for": "光，10%",
    "Mercenary.": "雇佣兵。",
    "None.": "一个也没有。",
    "Nudist": "裸体",
    "one-handed melee weapons is increased by 25%.": "单手近战武器增加25%。",
    "Perks": "津贴",
    "power level and thorns damage from": "能量等级和荆棘伤害来自",
    "power level.": "功率级。",
    "protection is increased by 20% for": "防护效果增加20%",
    "ranged weapon are": "远程武器",
    "reinforced and 5% for": "加强型和5%",
    "Renewal": "更新",
    "Retirement": "退休",
    "Sharpshooter": "神枪手",
    "shield is equipped,": "盾牌装备好了，",
    "shield.": "盾牌。",
    "Shredder": "碎纸机",
    "Skills trained by the": "培训的技能",
    "Stalwart": "勇者",
    "stamina and": "耐力和",
    "strength attribute rank.": "强度属性等级。",
    "stun chance is 3% per": "击晕的几率为3%",
    "Tank": "坦克",
    "thorns is determined by": "荆棘是由",
    "total damage is increased by 35% of current": "总伤害增加35%的当前伤害",
    "Trait selection": "特征选择",
    "two-handed melee weapon also have a chance to execute equivalent to the": "双手近战武器也有一定几率执行等同于",
    "Two-handed melee weapons can be equipped alongside a": "双手近战武器可以装备在",
    "unarmed,": "手无寸铁的,",
    "unarmored,": "没有盔甲，",
    "unshielded,": "无护盾，",
    "Until": "直到",
    "weapon damage of": "武器伤害",
    "Weary bones yearn for quiescence to foster a new beginning.": "疲惫的骨头渴望安静，以孕育一个新的开始。",
    "While a": "当",
    "While at a": "在一个",
    "Essence loot bonus": "精华战利品加成",
    "Infusable relic": "可灌注遗物",
    "Monster reduction": "怪物减少",
    "Starting essence": "初始精华",
    "Trait": "特征",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "neverquest": "永不冒险",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "v": "v",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Gems (": "宝石 (",
    "Burning": "燃烧",
    "Gaze into my cauldron": "凝视我的坩埚",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "Export savegame": "导出存档",
    "Import savegame": "导入存档",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) will be irretrievably destroyed.$/, '$1 将被不可挽回地摧毁。'],
    [/^(.+) will be lost forever.$/, '$1 将永远消失。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^encumbrance by ([\d\.,]+).$/, '负重上限 $1。'],
    [/^stage ([\d\.,]+).$/, '关卡 $1。'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);